### PR TITLE
Support ASN.1 RSAPublicKey type as defined by PKCS#1

### PR DESCRIPTION
**Pull request by HwangTaehyun**
Currently, the jsencrypt package only supports ASN.1 SubjectPublicKeyInfo type as defined by X.509.
However, many native platforms' RSA key libraries still only support ASN.1 RSAPublicKey type as defined by PKCS#1. Thus, we also need to support ASN.1 RSAPublicKey type as defined by PKCS#1.
Thanks @travist for the JavaScript RSA Encryption package!

### CODE REVIEW

**Comment by HwangTaehyun** [comment]
@travist Could you review this PR?

**Comment by HwangTaehyun** [comment]
ping @travist

**Comment by travist** [comment]
Looks good! Thank you!

Since this is a pretty large change, I would like to see some automated tests written for these changes for me to accept this into the library. Please add some tests and I would be happy to include this contribution. 

Thanks.

Travis.

**Comment by HwangTaehyun** [comment]
@travist Thanks! Could you let me know how to run the test code? Docs have no information about the test.

**Comment by HwangTaehyun** [comment]
Test code does not work, so I enable test code for local using chai & dirty-chai & ts-mocha and add test script to package.json. Also, I add the unit test for pkcs#1 format pub key. As the OpenSSL only exports pubkey by X509 format, I generate pkcs#1 format pub key using ssh-keygen with type RSA. I refer to https://www.rfc-editor.org/rfc/rfc4716#section-3.4, https://stackoverflow.com/questions/18039401/how-can-i-transform-between-the-two-styles-of-public-key-format-one-begin-rsa. 
Could you review the above code? @travist

**Comment by HwangTaehyun** [comment]
I would like to do this PR as part of [hacktoberfest](https://hacktoberfest.com/). Would you add the topic "hacktoberfest" to this PR?

**Comment by HwangTaehyun** [comment]
ping @travist 
Thanks!

**Comment by travist** [comment]
Done! Thank you and have fun at hacktoberfest!

**Comment by HwangTaehyun** [comment]
@travist Oh, thanks! but not title and this labels!
image

**Comment by HwangTaehyun** [comment]
Also, Could you review this PR?

**Comment by HwangTaehyun** [comment]
@travist I'm sorry to bother you :'
If I remember it correctly, the first requirement is that owner opt in their repository for the hacktoberfest by adding the hacktoberfest topic to the main repo. So, this is not recognized by hacktoberfest.
Would you add hacktoberfest topic to this repo? Many open-source developer would be happy that!

**Comment by HwangTaehyun** [comment]
@travist Oh, Sorry for that. I change package.json's type to module due to test code's esm.
Currently, I fixed all problems. Could you check this again? Thank you!

- Change webpack.config.js and webpack.prod.js to esm
- Change tsconfig-def.json's module to esnext
- Get version from process.env.npm_package_version

**Comment by HwangTaehyun** [comment]
@travist Could you review that? I checked them and all scripts currently work!

**Comment by travist** [comment]
Looks good!  Thanks!

**Comment by travist** [comment]
So I am not able to release this because it broke the application.

Try the following to reproduce...

 - Install Jekyll
 - Then run ```npm run serve```
 - Go to http://localhost:4000/demo/index.html
 - The following error occurs...

```
Uncaught TypeError: JSEncrypt is not a constructor
    at generateKeys (index.html:183:19)
    at HTMLDocument.<anonymous> (index.html:213:5)
    at c (jquery.min.js:4:26036)
    at Object.fireWith [as resolveWith] (jquery.min.js:4:26840)
    at Function.ready (jquery.min.js:4:3305)
    at HTMLDocument.q (jquery.min.js:4:717)
generateKeys @ index.html:183
(anonymous) @ index.html:213
c @ jquery.min.js:4
fireWith @ jquery.min.js:4
ready @ jquery.min.js:4
q @ jquery.min.js:4
```

Not sure what you changed that would affect that but it will block release...

**Comment by HwangTaehyun** [comment]
I'll check it now.
Sorry for that not checking Jekyll build.
Also, I'm going to add a pre-hook for checking commits later.

**Comment by HwangTaehyun** [comment]
I found out that bin/jsencrypt.min.js is breaking when build.

**Comment by HwangTaehyun** [comment]
When i remove the next line in webpack.config.js, then build successfully.
```
experiments: {
     outputModule: true,
 },
```

**Comment by HwangTaehyun** [comment]
I run out a problem getting the version in browser using process variable.
```
process.env.npm_package_version;
```

I changed the original code which gets the version from package.json because the test script does not work well.

I will fix it today.

**Comment by HwangTaehyun** [comment]
I opened new PR! #263 @travist

**Pull request merged**
