### PR TITLE
Corrects a missing parameter in the mouse entropy generator. The  par…

### PR DESCRIPTION
**Pull request by hilts-vaughan**
…ameter is not optional in many browsers.

I've put it against master as it's relatively safe (I've just included the default parameter). I'm using this library in an app that needs support for Firefox 6 and below. It would be good to get a point release with this fix in.

From MDN:

"Note: useCapture became optional only in more recent versions of the major browsers; for example, it was not optional prior to Firefox 6. You should provide this parameter for broadest compatibility."

### CODE REVIEW

**Comment by zoloft** [comment]
Looks good to me. Could you please make the same pull request to the library zoloft/jsencrypt-core-libs ? It will be used in the future versions as a base for this library.

**Comment by hilts-vaughan** [comment]
Will do. Thanks a lot.

**Comment by zoloft** [comment]
P.S. @travist you should update the version in the metadata for bower etc.

**Comment by travist** [comment]
@zoloft, bower updates based on tags that are pushed to the repo so @zoloft feel free to push the relevant tag and change the bower.json file to reflect the appropriate version. If npm also needs to be updated, I can push that to npm on my end.  Thanks.

**Pull request merged**
