### PR TITLE
rewrite to typescript

### PR DESCRIPTION
**Pull request by llCorvinSll**
rewrite almost all to ts
add typings
build with rollup to umd module
add tests for async operations

now then using script directly in browser JSEncrypt class imported via namespace `JSEnc` like

```
new JSEnc.JSEncrypt()
```

### CODE REVIEW

**Comment by llCorvinSll** [comment]
@travist  any suggestions about this?

**Comment by travist** [comment]
This is amazing and a phenomenal effort. I love TypeScript so I will pull this in and take a look at its viability. Considering how massive of a change this is, we will need to create a BETA version release.

Thanks again!

Travis.

**Comment by llCorvinSll** [comment]
Hi, when we can do it?

**Comment by llCorvinSll** [comment]
@travist, maybe 2.4.0-beta?

**Comment by travist** [comment]
Yes that sounds good. I will run some tests over the weekend and will make it happen

**Comment by llCorvinSll** [comment]
@travist Maybe make it?

**Comment by travist** [comment]
I just tested this out and it is brilliant!  Committing right now.  I have to make a few changes but will push up a new 2.x beta branch with this.

**Pull request merged**
