### PR TITLE
Fix npm packaging

### PR DESCRIPTION
**Pull request by matheo**
Version `v3.0.1` packaging doesn't enable Typescript frameworks like Angular to import `JSEncrypt` and mock it with Jest in the way `v3.0.0-beta.2` was bundled.

Exporting the `JSEncrypt` class next to the `default` export seems to work in Angular, and should work with your existing setup.

Also, `types` are missing in the `package.json` not allowing to have the definitions of the default export,
`main` should be used for the `umd` compiled code, and `module` for the `es6` code.

Looking forward for your feedback.
Thanks for this great lib!

### CODE REVIEW

**Comment by matheo** [comment]
You can test how it works checking `@matheo/jsencrypt` `v3.0.2`
my company might need to use my fork if this doesn't get addressed :(

**Comment by travist** [comment]
I will release this fix soon. Thanks!

**Comment by matheo** [comment]
Thank you!

**Comment by matheo** [comment]
@travist any blocker for the release?
my PR to update the dependenciesin my company is blocked by this one :(

**Comment by matheo** [comment]
Hmm even with this fix the package doesn't work with Storybook, I needed to setup `"main": "lib/JSEncrypt.js"` and `"types": "lib/JSEncrypt.d.ts"`... hmmm

**Pull request closed without merging**
